/* =========================================
   1. BANCO DE DADOS (CONFIGURAÇÃO)
   ========================================= */

// Cards Principais (Separados por Aba)
const mainCardsData = [
  //melhores sites
  {
    id: "pt.welib.st",
    category: "livros em pdf",
    name: "WeLib",
    desc: "WeLib – Biblioteca com milhões de livros e artigos gratuitos.",
    url: "https://pt.welib.st/",
    img: "https://pt.welib.st/favicon.ico",
  },
  {
    id: "gutenberg.org",
    category: "livros em pdf",
    name: "Project Gutenberg",
    desc: "Mais de 75 mil livros 100% gratuitos e legais em PDF.",
    url: "https://www.gutenberg.org/",
    img: "https://www.gutenberg.org/favicon.ico",
  },
  {
    id: "standardebooks.org",
    category: "livros em pdf",
    name: "Standard Ebooks",
    desc: "Livros clássicos em domínio público, bem formatados e gratuitos.",
    url: "https://standardebooks.org/",
    img: "https://standardebooks.org/assets/favicon-32x32.png",
  },
  {
    id: "openlibrary.org",
    category: "livros em pdf",
    name: "Open Library",
    desc: "Biblioteca aberta com empréstimos digitais e PDFs gratuitos.",
    url: "https://openlibrary.org/",
    img: "https://openlibrary.org/static/images/openlibrary-logo-tighter.svg",
  },
  {
    id: "internetarchive.org",
    category: "livros em pdf",
    name: "Internet Archive",
    desc: "Milhões de livros gratuitos em PDF e outros formatos.",
    url: "https://archive.org/",
    img: "https://archive.org/services/img/ia-logo.png",
  },
  {
    id: "dominiopublico.gov.br",
    category: "livros em pdf",
    name: "Domínio Público",
    desc: "Portal oficial do governo brasileiro com livros em PDF grátis.",
    url: "http://www.dominiopublico.gov.br/",
    img: "http://www.dominiopublico.gov.br/favicon.ico",
  },
  {
    id: "bndigital.bn.gov.br",
    category: "livros em pdf",
    name: "Biblioteca Nacional Digital",
    desc: "Livros históricos brasileiros totalmente gratuitos.",
    url: "https://bndigital.bn.gov.br/",
    img: "https://bndigital.bn.gov.br/favicon.ico",
  },
  {
    id: "manybooks.net",
    category: "livros em pdf",
    name: "ManyBooks",
    desc: "Coleção de livros de domínio público em PDF.",
    url: "https://manybooks.net/",
    img: "https://manybooks.net/favicon.ico",
  },
  {
    id: "readprint.com",
    category: "livros em pdf",
    name: "Read Print",
    desc: "Livros clássicos gratuitos para leitura e download.",
    url: "http://www.readprint.com/",
    img: "http://www.readprint.com/favicon.ico",
  },
  {
    id: "classicreader.com",
    category: "livros em pdf",
    name: "Classic Reader",
    desc: "Biblioteca de clássicos em domínio público.",
    url: "https://www.classicreader.com/",
    img: "https://www.classicreader.com/favicon.ico",
  },
  {
    id: "wdl.org",
    category: "livros em pdf",
    name: "Biblioteca Digital Mundial",
    desc: "Livros e documentos históricos gratuitos do mundo todo.",
    url: "https://www.wdl.org/",
    img: "https://www.wdl.org/favicon.ico",
  },
  {
    id: "baixelivros.com.br",
    category: "livros em pdf",
    name: "BaixeLivros",
    desc: "Livros em PDF gratuitos em português.",
    url: "https://www.baixelivros.com.br/",
    img: "https://www.baixelivros.com.br/favicon.ico",
  },
  {
    id: "dlivros.com",
    category: "livros em pdf",
    name: "dLivros",
    desc: "Livros gratuitos em PDF organizados por temas.",
    url: "https://www.dlivros.com/",
    img: "https://www.dlivros.com/favicon.ico",
  },
  {
    id: "livribox.com",
    category: "livros em pdf",
    name: "LivriBox",
    desc: "Audiolivros e livros digitais totalmente gratuitos.",
    url: "https://www.livribox.com/",
    img: "https://www.livribox.com/favicon.ico",
  },
  {
    id: "pt.wikisource.org",
    category: "livros em pdf",
    name: "Wikisource",
    desc: "Textos e livros livres em domínio público.",
    url: "https://pt.wikisource.org/",
    img: "https://pt.wikisource.org/favicon.ico",
  },
  {
    id: "books.google.com",
    category: "livros em pdf",
    name: "Google Books (Domínio Público)",
    desc: "Livros de domínio público disponíveis gratuitamente.",
    url: "https://books.google.com/",
    img: "https://books.google.com/favicon.ico",
  },
  {
    id: "ilovepdf.com",
    category: "ferramentas pdf",
    name: "iLovePDF",
    desc: "Unir, dividir, converter e comprimir PDFs online gratuitamente.",
    url: "https://www.ilovepdf.com/",
    img: "https://www.ilovepdf.com/favicon.ico",
  },
  {
    id: "smallpdf.com",
    category: "ferramentas pdf",
    name: "SmallPDF",
    desc: "Ferramentas simples para editar e converter PDFs.",
    url: "https://smallpdf.com/",
    img: "https://smallpdf.com/favicon.ico",
  },
  {
    id: "pdf24.org",
    category: "ferramentas pdf",
    name: "PDF24 Tools",
    desc: "Ferramentas gratuitas para criar, editar e converter PDF.",
    url: "https://tools.pdf24.org/",
    img: "https://tools.pdf24.org/favicon.ico",
  },
  {
    id: "sejda.com",
    category: "ferramentas pdf",
    name: "Sejda PDF",
    desc: "Editar, comprimir, dividir e assinar PDFs online.",
    url: "https://www.sejda.com/",
    img: "https://www.sejda.com/favicon.ico",
  },
  {
    id: "pdfescape.com",
    category: "ferramentas pdf",
    name: "PDFescape",
    desc: "Editar e preencher formulários PDF online.",
    url: "https://www.pdfescape.com/",
    img: "https://www.pdfescape.com/favicon.ico",
  },
  {
    id: "online2pdf.com",
    category: "ferramentas pdf",
    name: "Online2PDF",
    desc: "Converter documentos e imagens para PDF gratuitamente.",
    url: "https://online2pdf.com/",
    img: "https://online2pdf.com/favicon.ico",
  },
  {
    id: "pdfcandy.com",
    category: "ferramentas pdf",
    name: "PDF Candy",
    desc: "Mais de 40 ferramentas gratuitas para PDF.",
    url: "https://pdfcandy.com/",
    img: "https://pdfcandy.com/favicon.ico",
  },
  {
    id: "hipdf.com",
    category: "ferramentas pdf",
    name: "HiPDF",
    desc: "Converter, editar e proteger PDFs online.",
    url: "https://www.hipdf.com/",
    img: "https://www.hipdf.com/favicon.ico",
  },
  {
    id: "pdfsam.org",
    category: "ferramentas pdf",
    name: "PDFsam",
    desc: "Dividir e unir PDFs com software gratuito.",
    url: "https://pdfsam.org/",
    img: "https://pdfsam.org/favicon.ico",
  },
  {
    id: "docupub.com",
    category: "ferramentas pdf",
    name: "DocuPub",
    desc: "Converter documentos para PDF e Word.",
    url: "https://www.docupub.com/",
    img: "https://www.docupub.com/favicon.ico",
  },
  {
    id: "pdfconverter.com",
    category: "ferramentas pdf",
    name: "PDF Converter",
    desc: "Conversão rápida de arquivos para PDF.",
    url: "https://www.pdfconverter.com/",
    img: "https://www.pdfconverter.com/favicon.ico",
  },
  {
    id: "sodapdf.com",
    category: "ferramentas pdf",
    name: "Soda PDF",
    desc: "Editar e converter PDFs online.",
    url: "https://www.sodapdf.com/",
    img: "https://www.sodapdf.com/favicon.ico",
  },
  {
    id: "pdf2go.com",
    category: "ferramentas pdf",
    name: "PDF2Go",
    desc: "Editar PDFs direto no navegador.",
    url: "https://www.pdf2go.com/",
    img: "https://www.pdf2go.com/favicon.ico",
  },
  {
    id: "ilovepdf2.com",
    category: "ferramentas pdf",
    name: "iLovePDF2",
    desc: "Ferramentas alternativas para edição de PDF.",
    url: "https://www.ilovepdf2.com/",
    img: "https://www.ilovepdf2.com/favicon.ico",
  },
  {
    id: "pdfaid.com",
    category: "ferramentas pdf",
    name: "PDFAid",
    desc: "Converter PDFs para Word, Excel e imagens.",
    url: "https://www.pdfaid.com/",
    img: "https://www.pdfaid.com/favicon.ico",
  },
  {
    id: "cleverpdf.com",
    category: "ferramentas pdf",
    name: "CleverPDF",
    desc: "Ferramentas online e offline para PDFs.",
    url: "https://www.cleverpdf.com/",
    img: "https://www.cleverpdf.com/favicon.ico",
  },
  {
    id: "pdfbear.com",
    category: "ferramentas pdf",
    name: "PDFBear",
    desc: "Converter, comprimir e editar PDFs.",
    url: "https://www.pdfbear.com/",
    img: "https://www.pdfbear.com/favicon.ico",
  },
  {
    id: "pdfpro.com",
    category: "ferramentas pdf",
    name: "PDF Pro",
    desc: "Criar e editar PDFs online.",
    url: "https://www.pdfpro.com/",
    img: "https://www.pdfpro.com/favicon.ico",
  },
  {
    id: "lightpdf.com",
    category: "ferramentas pdf",
    name: "LightPDF",
    desc: "Editar, converter e assinar PDFs.",
    url: "https://lightpdf.com/",
    img: "https://lightpdf.com/favicon.ico",
  },
  {
    id: "pdfchef.com",
    category: "ferramentas pdf",
    name: "PDFChef",
    desc: "Ferramentas PDF simples e rápidas.",
    url: "https://www.pdfchef.com/",
    img: "https://www.pdfchef.com/favicon.ico",
  },
  {
    id: "pdfresizer.com",
    category: "ferramentas pdf",
    name: "PDF Resizer",
    desc: "Redimensionar e dividir PDFs gratuitamente.",
    url: "https://pdfresizer.com/",
    img: "https://pdfresizer.com/favicon.ico",
  },
  {
    id: "pdfcompressor.com",
    category: "ferramentas pdf",
    name: "PDF Compressor",
    desc: "Comprimir PDFs online sem perda de qualidade.",
    url: "https://pdfcompressor.com/",
    img: "https://pdfcompressor.com/favicon.ico",
  },
  {
    id: "freepdfconvert.com",
    category: "ferramentas pdf",
    name: "FreePDFConvert",
    desc: "Conversão gratuita de PDF para outros formatos.",
    url: "https://www.freepdfconvert.com/",
    img: "https://www.freepdfconvert.com/favicon.ico",
  },
  {
    id: "pdfio.co",
    category: "ferramentas pdf",
    name: "PDF.io",
    desc: "Ferramentas rápidas para manipular PDFs.",
    url: "https://pdf.io/",
    img: "https://pdf.io/favicon.ico",
  },
  {
    id: "avepdf.com",
    category: "ferramentas pdf",
    name: "AvePDF",
    desc: "Editar, proteger e converter PDFs online.",
    url: "https://www.avepdf.com/",
    img: "https://www.avepdf.com/favicon.ico",
  },
  {
    id: "pdfmerge.com",
    category: "ferramentas pdf",
    name: "PDF Merge",
    desc: "Unir vários PDFs em um só arquivo.",
    url: "https://pdfmerge.com/",
    img: "https://pdfmerge.com/favicon.ico",
  },
  {
    id: "pdfsplitter.com",
    category: "ferramentas pdf",
    name: "PDF Splitter",
    desc: "Separar páginas de PDF facilmente.",
    url: "https://pdfsplitter.com/",
    img: "https://pdfsplitter.com/favicon.ico",
  },
  {
    id: "pdfunlock.com",
    category: "ferramentas pdf",
    name: "PDF Unlock",
    desc: "Remover senha de PDFs gratuitamente.",
    url: "https://www.pdfunlock.com/",
    img: "https://www.pdfunlock.com/favicon.ico",
  },
  {
    id: "pdfcreator.org",
    category: "ferramentas pdf",
    name: "PDFCreator",
    desc: "Criar PDFs gratuitos no Windows.",
    url: "https://www.pdfforge.org/pdfcreator",
    img: "https://www.pdfforge.org/favicon.ico",
  },
  {
    id: "foxit.com",
    category: "ferramentas pdf",
    name: "Foxit PDF Tools",
    desc: "Ferramentas online gratuitas para PDFs.",
    url: "https://www.foxit.com/pdf-tools/",
    img: "https://www.foxit.com/favicon.ico",
  },
  {
    id: "photopea.com",
    category: "editar",
    name: "Photopea",
    desc: "Editor de fotos online estilo Photoshop, suporta PSD, JPG e PNG.",
    url: "https://www.photopea.com/",
    img: "https://www.photopea.com/favicon.ico",
  },
  {
    id: "pixlr.com",
    category: "editar",
    name: "Pixlr",
    desc: "Editor de fotos online rápido e poderoso com filtros e efeitos.",
    url: "https://pixlr.com/pt/",
    img: "https://pixlr.com/favicon.ico",
  },
  {
    id: "canva.com",
    category: "editar",
    name: "Canva",
    desc: "Editor de fotos e designs online fácil de usar.",
    url: "https://www.canva.com/",
    img: "https://www.canva.com/favicon.ico",
  },
  {
    id: "fotor.com",
    category: "editar",
    name: "Fotor",
    desc: "Editar fotos online com filtros, ajustes e colagens.",
    url: "https://www.fotor.com/",
    img: "https://www.fotor.com/favicon.ico",
  },
  {
    id: "befunky.com",
    category: "editar",
    name: "BeFunky",
    desc: "Editor criativo de fotos com efeitos e retoques.",
    url: "https://www.befunky.com/",
    img: "https://www.befunky.com/favicon.ico",
  },
  {
    id: "lunapic.com",
    category: "editar",
    name: "LunaPic",
    desc: "Editor de imagens simples com muitos efeitos.",
    url: "https://www.lunapic.com/",
    img: "https://www.lunapic.com/favicon.ico",
  },
  {
    id: "polarr.com",
    category: "editar",
    name: "Polarr",
    desc: "Editor avançado de fotos com controle de cores.",
    url: "https://www.polarr.com/",
    img: "https://www.polarr.com/favicon.ico",
  },
  {
    id: "sumo.app",
    category: "editar",
    name: "Sumo Paint",
    desc: "Editor de imagens online com ferramentas de pintura.",
    url: "https://sumo.app/paint",
    img: "https://sumo.app/favicon.ico",
  },
  {
    id: "ribbet.com",
    category: "editar",
    name: "Ribbet",
    desc: "Editor de fotos simples e rápido.",
    url: "https://www.ribbet.com/",
    img: "https://www.ribbet.com/favicon.ico",
  },
  {
    id: "ipiccy.com",
    category: "editar",
    name: "iPiccy",
    desc: "Editar fotos com filtros, texto e retoque.",
    url: "https://www.ipiccy.com/",
    img: "https://www.ipiccy.com/favicon.ico",
  },
  {
    id: "photokit.com",
    category: "editar",
    name: "PhotoKit",
    desc: "Editor online com ajustes rápidos de imagem.",
    url: "https://photokit.com/",
    img: "https://photokit.com/favicon.ico",
  },
  {
    id: "fotojet.com",
    category: "editar",
    name: "FotoJet",
    desc: "Editar fotos e criar colagens online.",
    url: "https://www.fotojet.com/",
    img: "https://www.fotojet.com/favicon.ico",
  },
  {
    id: "pho.to",
    category: "editar",
    name: "Pho.to",
    desc: "Editor automático com efeitos e correções.",
    url: "https://pho.to/",
    img: "https://pho.to/favicon.ico",
  },
  {
    id: "adobe.com/express",
    category: "editar",
    name: "Adobe Express",
    desc: "Editor de fotos online gratuito da Adobe.",
    url: "https://www.adobe.com/br/express/",
    img: "https://www.adobe.com/favicon.ico",
  },
  {
    id: "pixlr.com/e",
    category: "editar",
    name: "Pixlr E",
    desc: "Versão avançada do Pixlr para edição completa.",
    url: "https://pixlr.com/e/",
    img: "https://pixlr.com/favicon.ico",
  },
  {
    id: "pixlr.com/x",
    category: "editar",
    name: "Pixlr X",
    desc: "Versão simples do Pixlr para edições rápidas.",
    url: "https://pixlr.com/x/",
    img: "https://pixlr.com/favicon.ico",
  },
  {
    id: "remove.bg",
    category: "editar",
    name: "Remove.bg",
    desc: "Remover fundo de imagens automaticamente.",
    url: "https://www.remove.bg/",
    img: "https://www.remove.bg/favicon.ico",
  },
  {
    id: "cleanup.pictures",
    category: "editar",
    name: "Cleanup Pictures",
    desc: "Remover objetos indesejados das fotos.",
    url: "https://cleanup.pictures/",
    img: "https://cleanup.pictures/favicon.ico",
  },
  {
    id: "kapwing.com",
    category: "editar",
    name: "Kapwing Image Editor",
    desc: "Editor online para imagens e conteúdo visual.",
    url: "https://www.kapwing.com/",
    img: "https://www.kapwing.com/favicon.ico",
  },
  {
    id: "imglarger.com",
    category: "editar",
    name: "ImgLarger",
    desc: "Melhorar e redimensionar imagens online.",
    url: "https://imglarger.com/",
    img: "https://imglarger.com/favicon.ico",
  },
  {
    id: "picwish.com",
    category: "editar",
    name: "PicWish",
    desc: "Editor de imagens com IA para fundo e ajustes.",
    url: "https://picwish.com/",
    img: "https://picwish.com/favicon.ico",
  },
  {
    id: "github.com",
    category: "programação",
    name: "GitHub",
    desc: "Hospedagem de código e projetos open source.",
    url: "https://github.com/",
    img: "https://github.com/favicon.ico",
  },
  {
    id: "stackoverflow.com",
    category: "programação",
    name: "Stack Overflow",
    desc: "Perguntas e respostas para programadores.",
    url: "https://stackoverflow.com/",
    img: "https://stackoverflow.com/favicon.ico",
  },
  {
    id: "developer.mozilla.org",
    category: "programação",
    name: "MDN Web Docs",
    desc: "Documentação oficial de tecnologias web.",
    url: "https://developer.mozilla.org/",
    img: "https://developer.mozilla.org/favicon.ico",
  },
  {
    id: "w3schools.com",
    category: "programação",
    name: "W3Schools",
    desc: "Tutoriais práticos de programação.",
    url: "https://www.w3schools.com/",
    img: "https://www.w3schools.com/favicon.ico",
  },
  {
    id: "freecodecamp.org",
    category: "programação",
    name: "freeCodeCamp",
    desc: "Aprenda programação 100% grátis.",
    url: "https://www.freecodecamp.org/",
    img: "https://www.freecodecamp.org/favicon.ico",
  },
  {
    id: "codepen.io",
    category: "programação",
    name: "CodePen",
    desc: "Editor online para HTML, CSS e JS.",
    url: "https://codepen.io/",
    img: "https://codepen.io/favicon.ico",
  },
  {
    id: "jsfiddle.net",
    category: "programação",
    name: "JSFiddle",
    desc: "Testes rápidos de JavaScript online.",
    url: "https://jsfiddle.net/",
    img: "https://jsfiddle.net/favicon.ico",
  },
  {
    id: "replit.com",
    category: "programação",
    name: "Replit",
    desc: "Programação online em várias linguagens.",
    url: "https://replit.com/",
    img: "https://replit.com/favicon.ico",
  },
  {
    id: "codesandbox.io",
    category: "programação",
    name: "CodeSandbox",
    desc: "Ambiente moderno para projetos web.",
    url: "https://codesandbox.io/",
    img: "https://codesandbox.io/favicon.ico",
  },
  {
    id: "hackerrank.com",
    category: "programação",
    name: "HackerRank",
    desc: "Desafios e testes de programação.",
    url: "https://www.hackerrank.com/",
    img: "https://www.hackerrank.com/favicon.ico",
  },
  {
    id: "leetcode.com",
    category: "programação",
    name: "LeetCode",
    desc: "Desafios focados em entrevistas técnicas.",
    url: "https://leetcode.com/",
    img: "https://leetcode.com/favicon.ico",
  },
  {
    id: "dev.to",
    category: "programação",
    name: "DEV Community",
    desc: "Artigos e comunidade de desenvolvedores.",
    url: "https://dev.to/",
    img: "https://dev.to/favicon.ico",
  },
  {
    id: "gitlab.com",
    category: "programação",
    name: "GitLab",
    desc: "Repositórios Git com CI/CD.",
    url: "https://gitlab.com/",
    img: "https://gitlab.com/favicon.ico",
  },
  {
    id: "npmjs.com",
    category: "programação",
    name: "NPM",
    desc: "Gerenciador de pacotes JavaScript.",
    url: "https://www.npmjs.com/",
    img: "https://www.npmjs.com/favicon.ico",
  },
  {
    id: "roadmap.sh",
    category: "programação",
    name: "Roadmap.sh",
    desc: "Guias de estudo para programadores.",
    url: "https://roadmap.sh/",
    img: "https://roadmap.sh/favicon.ico",
  },
  {
    id: "postimages.org",
    category: "converter img",
    name: "Postimages",
    desc: "Hospedar imagens gratuitamente e gerar URLs diretas para compartilhar.",
    url: "https://postimages.org/",
    img: "https://postimages.org/favicon.ico",
  },

  {
    id: "convertio.co",
    category: "converter img",
    name: "Convertio",
    desc: "Converter imagens entre JPG, PNG, WEBP, GIF e outros formatos.",
    url: "https://convertio.co/pt/image-converter/",
    img: "https://convertio.co/favicon.ico",
  },
  {
    id: "iloveimg.com",
    category: "converter img",
    name: "iLoveIMG",
    desc: "Converter imagens online de forma rápida e gratuita.",
    url: "https://www.iloveimg.com/pt/converter-de-imagem",
    img: "https://www.iloveimg.com/favicon.ico",
  },
  {
    id: "cloudconvert.com",
    category: "converter img",
    name: "CloudConvert",
    desc: "Conversor avançado de imagens e arquivos.",
    url: "https://cloudconvert.com/image-converter",
    img: "https://cloudconvert.com/favicon.ico",
  },
  {
    id: "freeconvert.com",
    category: "converter img",
    name: "FreeConvert",
    desc: "Converter imagens online sem instalação.",
    url: "https://www.freeconvert.com/image-converter",
    img: "https://www.freeconvert.com/favicon.ico",
  },
  {
    id: "img2go.com",
    category: "converter img",
    name: "Img2Go",
    desc: "Converter e editar imagens diretamente no navegador.",
    url: "https://www.img2go.com/pt/converter-imagem",
    img: "https://www.img2go.com/favicon.ico",
  },
  {
    id: "online-convert.com",
    category: "converter img",
    name: "Online Convert",
    desc: "Conversão de imagens para vários formatos.",
    url: "https://image.online-convert.com/pt",
    img: "https://www.online-convert.com/favicon.ico",
  },
  {
    id: "resizepixel.com",
    category: "converter img",
    name: "ResizePixel",
    desc: "Converter e redimensionar imagens facilmente.",
    url: "https://www.resizepixel.com/pt",
    img: "https://www.resizepixel.com/favicon.ico",
  },
  {
    id: "pics.io/convert",
    category: "converter img",
    name: "Pics.io Convert",
    desc: "Conversão rápida de imagens online.",
    url: "https://pics.io/convert",
    img: "https://pics.io/favicon.ico",
  },
  {
    id: "imageconverterplus.com",
    category: "converter img",
    name: "Image Converter Plus",
    desc: "Conversor simples de formatos de imagem.",
    url: "https://www.imageconverterplus.com/online/",
    img: "https://www.imageconverterplus.com/favicon.ico",
  },
  {
    id: "zamzar.com",
    category: "converter img",
    name: "Zamzar",
    desc: "Converter imagens e outros arquivos online.",
    url: "https://www.zamzar.com/convert/image/",
    img: "https://www.zamzar.com/favicon.ico",
  },
  {
    id: "fonts.google.com",
    category: "fontes",
    name: "Google Fonts",
    desc: "Biblioteca gratuita de fontes para uso em sites.",
    url: "https://fonts.google.com/",
    img: "https://fonts.google.com/favicon.ico",
  },
  {
    id: "dafont.com",
    category: "fontes",
    name: "DaFont",
    desc: "Milhares de fontes gratuitas para download.",
    url: "https://www.dafont.com/",
    img: "https://www.dafont.com/favicon.ico",
  },
  {
    id: "fontsquirrel.com",
    category: "fontes",
    name: "Font Squirrel",
    desc: "Fontes gratuitas para uso comercial.",
    url: "https://www.fontsquirrel.com/",
    img: "https://www.fontsquirrel.com/favicon.ico",
  },
  {
    id: "theleagueofmovabletype.com",
    category: "fontes",
    name: "The League of Movable Type",
    desc: "Fontes open source de alta qualidade.",
    url: "https://www.theleagueofmovabletype.com/",
    img: "https://www.theleagueofmovabletype.com/favicon.ico",
  },
  {
    id: "velvetyne.fr",
    category: "fontes",
    name: "Velvetyne Type Foundry",
    desc: "Fontes open source e experimentais.",
    url: "https://velvetyne.fr/",
    img: "https://velvetyne.fr/favicon.ico",
  },
  {
    id: "fonts.adobe.com",
    category: "fontes",
    name: "Adobe Fonts",
    desc: "Fontes profissionais para web e design.",
    url: "https://fonts.adobe.com/",
    img: "https://fonts.adobe.com/favicon.ico",
  },
  {
    id: "fontspace.com",
    category: "fontes",
    name: "FontSpace",
    desc: "Fontes gratuitas para designers e desenvolvedores.",
    url: "https://www.fontspace.com/",
    img: "https://www.fontspace.com/favicon.ico",
  },
  {
    id: "fontbundles.net",
    category: "fontes",
    name: "Font Bundles",
    desc: "Pacotes de fontes gratuitas e premium.",
    url: "https://fontbundles.net/free-fonts",
    img: "https://fontbundles.net/favicon.ico",
  },
  {
    id: "urbanfonts.com",
    category: "fontes",
    name: "Urban Fonts",
    desc: "Fontes gratuitas para uso pessoal e comercial.",
    url: "https://www.urbanfonts.com/",
    img: "https://www.urbanfonts.com/favicon.ico",
  },
  {
    id: "fontsarena.com",
    category: "fontes",
    name: "Fonts Arena",
    desc: "Fontes gratuitas de alta qualidade.",
    url: "https://fontsarena.com/",
    img: "https://fontsarena.com/favicon.ico",
  },
  {
    id: "fontlibrary.org",
    category: "fontes",
    name: "Font Library",
    desc: "Biblioteca open source de fontes.",
    url: "https://fontlibrary.org/",
    img: "https://fontlibrary.org/favicon.ico",
  },
  {
    id: "1001fonts.com",
    category: "fontes",
    name: "1001 Fonts",
    desc: "Grande coleção de fontes gratuitas.",
    url: "https://www.1001fonts.com/",
    img: "https://www.1001fonts.com/favicon.ico",
  },
  {
    id: "fontfabric.com",
    category: "fontes",
    name: "Fontfabric",
    desc: "Fontes modernas para uso web.",
    url: "https://www.fontfabric.com/free-fonts/",
    img: "https://www.fontfabric.com/favicon.ico",
  },
  {
    id: "collletttivo.it",
    category: "fontes",
    name: "Collletttivo",
    desc: "Fontes open source feitas por designers.",
    url: "https://www.collletttivo.it/",
    img: "https://www.collletttivo.it/favicon.ico",
  },
  {
    id: "open-foundry.com",
    category: "fontes",
    name: "Open Foundry",
    desc: "Fontes gratuitas e open source.",
    url: "https://open-foundry.com/",
    img: "https://open-foundry.com/favicon.ico",
  },
  {
    id: "usemodify.com",
    category: "fontes",
    name: "Modify",
    desc: "Fontes open source para web.",
    url: "https://usemodify.com/",
    img: "https://usemodify.com/favicon.ico",
  },

  {
    id: "menu-nav-11-1",

    category: "icones sites",
    name: "Menu Nav 11-1",
    desc: "Animação de menu hambúrguer profissional que se transforma em 'X'. Ideal para navegação mobile com transição suave.",
    url: "https://finsweet.com/lottieflow/download/menu-nav-11-1",
    img: "https://cdn.prod.website-files.com/5d829bf092d4644f5c42e0ea/5e0df3c7574de27fd9eb5319_Menu1-MenuNavPack-smooth.json",
    
  },

  {
    id: "flaticon.com",
    category: "icones sites",
    name: "Flaticon",
    desc: "Milhões de ícones gratuitos em SVG, PNG e mais.",
    url: "https://www.flaticon.com/",
    img: "https://www.flaticon.com/favicon.ico",
  },
  {
    id: "fontawesome.com",
    category: "icones sites",
    name: "Font Awesome",
    desc: "Biblioteca popular de ícones para web.",
    url: "https://fontawesome.com/",
    img: "https://fontawesome.com/favicon.ico",
  },
  {
    id: "icons.getbootstrap.com",
    category: "icones sites",
    name: "Bootstrap Icons",
    desc: "Ícones oficiais do Bootstrap em SVG.",
    url: "https://icons.getbootstrap.com/",
    img: "https://icons.getbootstrap.com/favicon.ico",
  },
  {
    id: "heroicons.com",
    category: "icones sites",
    name: "Heroicons",
    desc: "Ícones SVG modernos para interfaces.",
    url: "https://heroicons.com/",
    img: "https://heroicons.com/favicon.ico",
  },
  {
    id: "material.io/icons",
    category: "icones sites",
    name: "Material Icons",
    desc: "Ícones oficiais do Google Material Design.",
    url: "https://fonts.google.com/icons",
    img: "https://fonts.google.com/favicon.ico",
  },
  {
    id: "ionic.io/ionicons",
    category: "icones sites",
    name: "Ionicons",
    desc: "Ícones premium para apps e sites.",
    url: "https://ionic.io/ionicons",
    img: "https://ionic.io/favicon.ico",
  },
  {
    id: "tabler-icons.io",
    category: "icones sites",
    name: "Tabler Icons",
    desc: "Ícones SVG open source e leves.",
    url: "https://tabler-icons.io/",
    img: "https://tabler-icons.io/favicon.ico",
  },
  {
    id: "feathericons.com",
    category: "icones sites",
    name: "Feather Icons",
    desc: "Ícones minimalistas em SVG.",
    url: "https://feathericons.com/",
    img: "https://feathericons.com/favicon.ico",
  },
  {
    id: "iconscout.com",
    category: "icones sites",
    name: "Iconscout",
    desc: "Ícones gratuitos e premium.",
    url: "https://iconscout.com/",
    img: "https://iconscout.com/favicon.ico",
  },
  {
    id: "thenounproject.com",
    category: "icones sites",
    name: "The Noun Project",
    desc: "Ícones criados por designers do mundo todo.",
    url: "https://thenounproject.com/",
    img: "https://thenounproject.com/favicon.ico",
  },
  {
    id: "svgrepo.com",
    category: "icones sites",
    name: "SVG Repo",
    desc: "Ícones SVG gratuitos e open source.",
    url: "https://www.svgrepo.com/",
    img: "https://www.svgrepo.com/favicon.ico",
  },
  {
    id: "iconfinder.com",
    category: "icones sites",
    name: "IconFinder",
    desc: "Buscar ícones profissionais para projetos.",
    url: "https://www.iconfinder.com/",
    img: "https://www.iconfinder.com/favicon.ico",
  },
  {
    id: "icons8.com",
    category: "icones sites",
    name: "Icons8",
    desc: "Ícones, ilustrações e emojis.",
    url: "https://icons8.com/icons",
    img: "https://icons8.com/favicon.ico",
  },
  {
    id: "remixicon.com",
    category: "icones sites",
    name: "Remix Icon",
    desc: "Ícones open source para interfaces modernas.",
    url: "https://remixicon.com/",
    img: "https://remixicon.com/favicon.ico",
  },
  {
    id: "boxicons.com",
    category: "icones sites",
    name: "Boxicons",
    desc: "Ícones simples e gratuitos.",
    url: "https://boxicons.com/",
    img: "https://boxicons.com/favicon.ico",
  },
  {
    id: "lineicons.com",
    category: "icones sites",
    name: "Lineicons",
    desc: "Ícones em linha para web e apps.",
    url: "https://lineicons.com/",
    img: "https://lineicons.com/favicon.ico",
  },
  {
    id: "css.gg",
    category: "icones sites",
    name: "CSS.gg",
    desc: "Ícones CSS e SVG gratuitos.",
    url: "https://css.gg/",
    img: "https://css.gg/favicon.ico",
  },
  {
    id: "iconmonstr.com",
    category: "icones sites",
    name: "Iconmonstr",
    desc: "Ícones simples e diretos.",
    url: "https://iconmonstr.com/",
    img: "https://iconmonstr.com/favicon.ico",
  },
  {
    id: "phosphoricons.com",
    category: "icones sites",
    name: "Phosphor Icons",
    desc: "Ícones flexíveis para interfaces modernas.",
    url: "https://phosphoricons.com/",
    img: "https://phosphoricons.com/favicon.ico",
  },
  {
    id: "akaricons.com",
    category: "icones sites",
    name: "Akar Icons",
    desc: "Ícones open source minimalistas.",
    url: "https://akaricons.com/",
    img: "https://akaricons.com/favicon.ico",
  },
  {
    id: "simpleicons.org",
    category: "icones sites",
    name: "Simple Icons",
    desc: "Ícones de marcas e tecnologias.",
    url: "https://simpleicons.org/",
    img: "https://simpleicons.org/favicon.ico",
  },
  {
    id: "devicon.dev",
    category: "icones sites",
    name: "Devicon",
    desc: "Ícones de linguagens e ferramentas de programação.",
    url: "https://devicon.dev/",
    img: "https://devicon.dev/favicon.ico",
  },
  {
    id: "iconoir.com",
    category: "icones sites",
    name: "Iconoir",
    desc: "Ícones open source feitos à mão.",
    url: "https://iconoir.com/",
    img: "https://iconoir.com/favicon.ico",
  },
  {
    id: "uxwing.com",
    category: "icones sites",
    name: "UXWing",
    desc: "Ícones gratuitos para uso comercial.",
    url: "https://uxwing.com/",
    img: "https://uxwing.com/favicon.ico",
  },
  {
    id: "iconsax.io",
    category: "icones sites",
    name: "Iconsax",
    desc: "Ícones modernos para UI/UX.",
    url: "https://iconsax.io/",
    img: "https://iconsax.io/favicon.ico",
  },
  {
    id: "iconhub.io",
    category: "icones sites",
    name: "Iconhub",
    desc: "Ícones gratuitos em SVG.",
    url: "https://iconhub.io/",
    img: "https://iconhub.io/favicon.ico",
  },
  {
    id: "svgl.app",
    category: "icones sites",
    name: "SVGL",
    desc: "Ícones SVG de marcas famosas.",
    url: "https://svgl.app/",
    img: "https://svgl.app/favicon.ico",
  },
  {
    id: "lordicon.com",
    category: "icones sites",
    name: "Lordicon",
    desc: "Ícones animados para web.",
    url: "https://lordicon.com/",
    img: "https://lordicon.com/favicon.ico",
  },
  {
    id: "animatedicons.co",
    category: "icones sites",
    name: "Animated Icons",
    desc: "Ícones animados em JSON e GIF.",
    url: "https://animatedicons.co/",
    img: "https://animatedicons.co/favicon.ico",
  },
  {
    id: "iconsvg.xyz",
    category: "icones sites",
    name: "IconSVG",
    desc: "Ícones SVG gratuitos.",
    url: "https://iconsvg.xyz/",
    img: "https://iconsvg.xyz/favicon.ico",
  },
  {
    id: "iconarchive.com",
    category: "icones sites",
    name: "IconArchive",
    desc: "Arquivo com milhares de ícones.",
    url: "https://iconarchive.com/",
    img: "https://iconarchive.com/favicon.ico",
  },
  {
    id: "freeicons.io",
    category: "icones sites",
    name: "FreeIcons",
    desc: "Ícones gratuitos para projetos.",
    url: "https://freeicons.io/",
    img: "https://freeicons.io/favicon.ico",
  },
  {
    id: "iconduck.com",
    category: "icones sites",
    name: "Iconduck",
    desc: "Ícones open source em SVG.",
    url: "https://iconduck.com/",
    img: "https://iconduck.com/favicon.ico",
  },
  {
    id: "icofont.com",
    category: "icones sites",
    name: "IcoFont",
    desc: "Ícones em formato de fonte.",
    url: "https://icofont.com/",
    img: "https://icofont.com/favicon.ico",
  },
  {
    id: "iconset.io",
    category: "icones sites",
    name: "Iconset",
    desc: "Buscar ícones por coleções.",
    url: "https://iconset.io/",
    img: "https://iconset.io/favicon.ico",
  },
  {
    id: "iconsvg.com",
    category: "icones sites",
    name: "IconSVG",
    desc: "Gerar e baixar ícones SVG.",
    url: "https://iconsvg.com/",
    img: "https://iconsvg.com/favicon.ico",
  },
  {
    id: "iconshock.com",
    category: "icones sites",
    name: "Iconshock",
    desc: "Ícones profissionais e gratuitos.",
    url: "https://www.iconshock.com/",
    img: "https://www.iconshock.com/favicon.ico",
  },
  {
    id: "freepik.com/icons",
    category: "icones sites",
    name: "Freepik Icons",
    desc: "Coleção de ícones modernos.",
    url: "https://www.freepik.com/icons",
    img: "https://www.freepik.com/favicon.ico",
  },
  {
    id: "vecteezy.com",
    category: "icones sites",
    name: "Vecteezy",
    desc: "Ícones vetoriais gratuitos.",
    url: "https://www.vecteezy.com/free-icons",
    img: "https://www.vecteezy.com/favicon.ico",
  },
  {
    id: "iconsdb.com",
    category: "icones sites",
    name: "IconsDB",
    desc: "Ícones em PNG e ICO.",
    url: "https://www.iconsdb.com/",
    img: "https://www.iconsdb.com/favicon.ico",
  },
  {
    id: "icon-icons.com",
    category: "icones sites",
    name: "Icon-Icons",
    desc: "Grande base de ícones gratuitos.",
    url: "https://icon-icons.com/",
    img: "https://icon-icons.com/favicon.ico",
  },
  {
    id: "svgporn.com",
    category: "icones sites",
    name: "SVG Porn",
    desc: "Ícones SVG de tecnologias.",
    url: "https://svgporn.com/",
    img: "https://svgporn.com/favicon.ico",
  },
  {
    id: "favicon.io",
    category: "icones sites",
    name: "Favicon.io",
    desc: "Gerador gratuito de ícones e favicons para sites a partir de imagens, texto ou emojis.",
    url: "https://favicon.io/",
    img: "https://favicon.io/favicon.ico",
  },
  {
    id: "certificadocursosonline.com",
    category: "curso gratis",
    name: "Certificado Cursos Online",
    desc: "Plataforma com +280 cursos online gratuitos com acesso 24/7 e opção de certificado digital mediante taxa administrativa. Cursos em diversas áreas como informática, gestão e saúde.",
    url: "https://certificadocursosonline.com/",
    img: "https://www.google.com/s2/favicons?sz=64&domain=certificadocursosonline.com",
  },

  {
    id: "freecodecamp.org",
    category: "curso gratis",
    name: "freeCodeCamp",
    desc: "Cursos gratuitos de programação com certificados.",
    url: "https://www.freecodecamp.org/",
    img: "https://www.freecodecamp.org/favicon.ico",
  },
  {
    id: "coursera.org",
    category: "curso gratis",
    name: "Coursera",
    desc: "Cursos gratuitos de universidades (modo ouvinte).",
    url: "https://www.coursera.org/",
    img: "https://www.coursera.org/favicon.ico",
  },
  {
    id: "edx.org",
    category: "curso gratis",
    name: "edX",
    desc: "Cursos gratuitos de Harvard, MIT e outras.",
    url: "https://www.edx.org/",
    img: "https://www.edx.org/favicon.ico",
  },
  {
    id: "khanacademy.org",
    category: "curso gratis",
    name: "Khan Academy",
    desc: "Cursos gratuitos de matemática, programação e mais.",
    url: "https://pt.khanacademy.org/",
    img: "https://pt.khanacademy.org/favicon.ico",
  },
  {
    id: "udemy.com",
    category: "curso gratis",
    name: "Udemy (Grátis)",
    desc: "Cursos gratuitos em várias áreas.",
    url: "https://www.udemy.com/courses/free/",
    img: "https://www.udemy.com/favicon.ico",
  },
  {
    id: "alison.com",
    category: "curso gratis",
    name: "Alison",
    desc: "Cursos gratuitos com certificado opcional.",
    url: "https://alison.com/",
    img: "https://alison.com/favicon.ico",
  },
  {
    id: "fundacaobradesco.org.br",
    category: "curso gratis",
    name: "Fundação Bradesco",
    desc: "Cursos gratuitos em tecnologia e negócios.",
    url: "https://www.ev.org.br/",
    img: "https://www.ev.org.br/favicon.ico",
  },
  {
    id: "sebrae.com.br",
    category: "curso gratis",
    name: "Sebrae",
    desc: "Cursos gratuitos de empreendedorismo.",
    url: "https://www.sebrae.com.br/sites/PortalSebrae/cursosonline",
    img: "https://www.sebrae.com.br/favicon.ico",
  },
  {
    id: "rocketseat.com.br",
    category: "curso gratis",
    name: "Rocketseat",
    desc: "Cursos gratuitos de programação e tecnologia.",
    url: "https://www.rocketseat.com.br/",
    img: "https://www.rocketseat.com.br/favicon.ico",
  },
  {
    id: "dio.me",
    category: "curso gratis",
    name: "DIO",
    desc: "Cursos e bootcamps gratuitos de tecnologia.",
    url: "https://www.dio.me/",
    img: "https://www.dio.me/favicon.ico",
  },
  {
    id: "senai.br",
    category: "curso gratis",
    name: "SENAI",
    desc: "Cursos gratuitos e profissionalizantes.",
    url: "https://www.portaldaindustria.com.br/senai/",
    img: "https://www.portaldaindustria.com.br/favicon.ico",
  },
  {
    id: "ifrs.edu.br",
    category: "curso gratis",
    name: "IFRS",
    desc: "Cursos gratuitos online de instituições federais.",
    url: "https://moodle.ifrs.edu.br/",
    img: "https://ifrs.edu.br/favicon.ico",
  },
  {
    id: "udacity.com",
    category: "curso gratis",
    name: "Udacity (Free)",
    desc: "Cursos gratuitos de tecnologia.",
    url: "https://www.udacity.com/courses/all",
    img: "https://www.udacity.com/favicon.ico",
  },
  {
    id: "codecademy.com",
    category: "curso gratis",
    name: "Codecademy",
    desc: "Cursos gratuitos de programação (plano free).",
    url: "https://www.codecademy.com/",
    img: "https://www.codecademy.com/favicon.ico",
  },
  {
    id: "open.edu",
    category: "curso gratis",
    name: "OpenLearn",
    desc: "Cursos gratuitos da Open University.",
    url: "https://www.open.edu/openlearn/",
    img: "https://www.open.edu/favicon.ico",
  },
];
